// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdshtrUmpAA00DWFkfS3SFzH_z1wjB9bA',
    appId: '1:618782023998:web:a12a00ed7d2384a9fd0c6f',
    messagingSenderId: '618782023998',
    projectId: 'ble-attendance-f33fc',
    authDomain: 'ble-attendance-f33fc.firebaseapp.com',
    storageBucket: 'ble-attendance-f33fc.firebasestorage.app',
    measurementId: 'G-743EXSZHVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFJ_0TfRGWrTkpWnLIQb_f0iZ2TgzLchk',
    appId: '1:618782023998:android:6306c3106e412216fd0c6f',
    messagingSenderId: '618782023998',
    projectId: 'ble-attendance-f33fc',
    storageBucket: 'ble-attendance-f33fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTEOUSJW3OJjbjVJYj0eAQdl3yx9f-JgY',
    appId: '1:618782023998:ios:37917b4a3f040771fd0c6f',
    messagingSenderId: '618782023998',
    projectId: 'ble-attendance-f33fc',
    storageBucket: 'ble-attendance-f33fc.firebasestorage.app',
    iosBundleId: 'com.example.ble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTEOUSJW3OJjbjVJYj0eAQdl3yx9f-JgY',
    appId: '1:618782023998:ios:37917b4a3f040771fd0c6f',
    messagingSenderId: '618782023998',
    projectId: 'ble-attendance-f33fc',
    storageBucket: 'ble-attendance-f33fc.firebasestorage.app',
    iosBundleId: 'com.example.ble',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdshtrUmpAA00DWFkfS3SFzH_z1wjB9bA',
    appId: '1:618782023998:web:d66330182e377a1efd0c6f',
    messagingSenderId: '618782023998',
    projectId: 'ble-attendance-f33fc',
    authDomain: 'ble-attendance-f33fc.firebaseapp.com',
    storageBucket: 'ble-attendance-f33fc.firebasestorage.app',
    measurementId: 'G-N2MXQMG7WC',
  );
}
